#!/usr/bin/env python

import sys
import os

RENDER_GEXF_PATH = os.getenv("RENDER_GEXF_PATH") or "../semantic-graph.py/render-gexf.py"

js_path = sys.argv[1]
output_dir = None
if len(sys.argv) > 2:
    final_output_dir = sys.argv[2]
else:
    final_output_dir = "/tmp"

tmp_out_prefix = "/tmp/" + os.path.basename(js_path).replace(".js", "")

gexf_out = tmp_out_prefix + ".gexf"
dot_out = tmp_out_prefix + ".dot"
png_out = final_output_dir + "/" + os.path.basename(js_path).replace(".js", ".png")

def command(cmd):
    print(cmd)
    os.system(cmd)

command("./js2graph " + js_path + " " + gexf_out)
command("python " + RENDER_GEXF_PATH + " " + gexf_out)
command("dot -Tpng " + dot_out + " -o " + png_out)
if len(sys.argv) < 2:
    command("open " + png_out)
    print("Opened png at " + png_out)
