#!/usr/bin/env python

import sys
import os

RENDER_GEXF_PATH = os.getenv("RENDER_GEXF_PATH") or "../semantic-graph.py/render-gexf.py"

js_path = sys.argv[1]
tmp_out_prefix = "/tmp/" + os.path.basename(js_path).replace(".js", "")

gexf_out = tmp_out_prefix + ".gexf"
dot_out = tmp_out_prefix + ".dot"
pdf_out = tmp_out_prefix + ".pdf"

def command(cmd):
    print(cmd)
    os.system(cmd)

command("./js2graph " + js_path + " " + gexf_out)
command("python " + RENDER_GEXF_PATH + " " + gexf_out)
command("dot -Tpdf " + dot_out + " -o " + pdf_out)
command("open " + pdf_out)
print("Opened PDF at " + pdf_out)
